### ISSUE TITLE
Merge upstream patch "fix custom datadir/conf" - KomodoPlatform/komodo #209

### ISSUE THREAD

**Issue by mattmill30** [ip-gpu/KomodoOcean#59]
It's not readily apparent which projects have been merged into the original commit for this repository, so I'm working off intuition that the repository is a merger of https://github.com/KomodoPlatform/komodo and a pre-ArgsManager bitcoin-core fork, though it would be useful for the history to be documented in order to understand how the repository was constructed.

The first commit https://github.com/ip-gpu/KomodoOcean/commit/d14e33bc2829f95b8aac265d54c872749a977a9a includes a command-line -conf handling bug introduced into jl777/komodo on Oct 29, 2016 - https://github.com/jl777/komodo/commit/323832c3c3d6317d14e94964066e595208083ce6#diff-449acf764318b0ca96972daf8d28a28af79ad2c3381044851f2953792fcd8eef - as part of the dPoW implementation merge https://github.com/jl777/komodo/pull/45, before being forked into KomodoPlatform/komodo, which was subsequently resolved by @ca333 on Oct 21, 2019 https://github.com/KomodoPlatform/komodo/pull/209 with https://github.com/KomodoPlatform/komodo/pull/209/commits/7b20725cf472adcb0f5e5e6da27d2b505402c23e

Please merge https://github.com/KomodoPlatform/komodo/pull/209 to ensure the komodo daemon always handles -conf if it is specified on the command-line.

**Comment by TheComputerGenie** [comment]
This was addressed with #67 and should be closed
